---
title: "Linear Models"
output: github_document
---
```{r}
library(tidyverse)
library(p8105.datasets)
```

```{r}
data("nyc_airbnb") 

nyc_airbnb <-
  nyc_airbnb |>
  mutate(stars = review_scores_location / 2) |>
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |>
  filter(borough != "Staten Island") |>
  select(price, stars, borough, neighborhood, room_type)
  
```

```{r}
nyc_airbnb |>
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```


Look at the model we care about

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Let's look at the result...


```{r, include = FALSE}
fit
summary(fit)
summary(fit)$coef
coef(fit)
residuals(fit)
```


Lets look at the result bettter...

```{r}
broom::glance(fit)


broom::tidy(fit) |>
  select(-std.error, -statistic) |>
    mutate(
      term = str_replace(term, "borough", "Borough: ")
    ) |>
    knitr::kable(digits = 3)


```

##Be in control of factors 
```{r}
nyc_airbnb <- 
  nyc_airbnb |>
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```

Lets look at the plot again
```{r}
nyc_airbnb |>
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```


```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

broom::tidy(fit)

broom::glance(fit)
```




























